name: Main workflow
on:
  push:
    branches:
      - main
jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    #### Добавьте шаг с Flyway-миграциями
    - name: Flyway-install
      run: |
        docker run --rm --network host \
        -v "${GITHUB_WORKSPACE}/migrations:/flyway/sql:ro" \
        flyway/flyway:11.12.0 \
        -locations="filesystem:/flyway/sql" \
        -url="jdbc:postgresql://127.0.0.1:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}" \
        -user="${{ secrets.DB_USER }}" \
        -password="${{ secrets.DB_PASSWORD }}" \
        -baselineOnMigrate="true" \
        -validateMigrationNaming="true" \
        migrate
    ### Этот шаг оставьте без изменений
    - name: Download and setup autotests binaries
      run: |
        wget -qO- cloud-services-engineer.gitlab.yandexcloud.net/practicum-cloud-services/dbops-autotests/-/package_files/1/download > dbopstest
        chmod +x ./dbopstest
        mv ./dbopstest /usr/local/bin/dbopstest

    ### Этот шаг оставьте без изменений
    - name: Test
      run: |
        dbopstest \
          -test.v \
          -host=${{ secrets.DB_HOST }} \
          -port=${{ secrets.DB_PORT }} \
          -user=${{ secrets.DB_USER }} \
          -password=${{ secrets.DB_PASSWORD }} \
          -db=${{ secrets.DB_NAME }}
