name: Main workflow
on:
  push:
    branches:
      - main
jobs:
  migrate:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    #### Добавьте шаг с Flyway-миграциями
    - name: Flyway migrate
      uses: flyway/flyway-action@v3
      with:
        url: jdbc:postgresql://127.0.0.1:${{ secrets.DB_PORT }}/store
        user: ${{ secrets.DB_USER }}
        password: ${{ secrets.DB_PASSWORD }}
        locations: filesystem:${{ github.workspace }}/migrations
        baselineOnMigrate: true
        validateMigrationNaming: true
        command: migrate
    ### Этот шаг оставьте без изменений
    - name: Download and setup autotests binaries
      run: |
        wget -qO- cloud-services-engineer.gitlab.yandexcloud.net/practicum-cloud-services/dbops-autotests/-/package_files/1/download > dbopstest
        chmod +x ./dbopstest
        mv ./dbopstest /usr/local/bin/dbopstest

    ### Этот шаг оставьте без изменений
    - name: Test
      run: |
        dbopstest \
          -test.v \
          -host=${{ secrets.DB_HOST }} \
          -port=${{ secrets.DB_PORT }} \
          -user=${{ secrets.DB_USER }} \
          -password=${{ secrets.DB_PASSWORD }} \
          -db=${{ secrets.DB_NAME }}
