name: Main workflow
on:
  push:
    branches:
      - main
jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Start PostgreSQL with docker compose
      run: |
        echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" > .env  
        echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
        echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
        docker compose up -d
        
    - name: Postgres ready-check
      run: |
        until docker exec postgres pg_isready -U user; do
          sleep 1
        done
        echo "Postgres is ready!"
      
      #### Самый первый шаг из ридмишки
    - name: DB initialize
      run: |
        docker exec -u postgres postgres psql -U ${{ secrets.POSTGRES_USER }} -d ${{ secrets.POSTGRES_DB }} -c "CREATE DATABASE ${{ secrets.DB_NAME }}"

    #### Добавьте шаг с Flyway-миграциями
    

    ### Этот шаг оставьте без изменений
    - name: Test
      run: |
        dbopstest \
          -test.v \
          -host=${{ secrets.DB_HOST }} \
          -port=${{ secrets.DB_PORT }} \
          -user=${{ secrets.DB_USER }} \
          -password=${{ secrets.DB_PASSWORD }} \
          -db=${{ secrets.DB_NAME }}
